#!/bin/bash
    echo "Starting file $file at `date`" >> Status
    export g16root=/home/user/softwares/g16
    export GAUSS_SCRDIR=/home/user/scratch
    export GAUSS_EXEDIR=$g16root/g16
    . $g16root/g16/bsd/g16.profile

    g16 < methToluene.com > methToluene.log  # Change the filename g16 < input-filename.com > output-filename.log
    echo "$file Done with status $status" >> Status
echo "All Done." >> Status
