#!/bin/bash
    echo "Starting file $file at `date`" >> Status
    export g16root=/home/user/softwares/g16
    export GAUSS_SCRDIR=/home/user/scratch
    export GAUSS_EXEDIR=$g16root/g16
    . $g16root/g16/bsd/g16.profile

    g16 < C6H6.com > C6H6.log
    echo "$file Done with status $status" >> Status
echo "All Done." >> Status
